// import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { UserContextProvider } from "./contexts/UserContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserContextProvider>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={ `antialiased `}
      >
        {children}
      </body>
      </UserContextProvider>
    </html>
  );
}
